package cmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate a fhirlint.yml config file in the current directory",
	Long: `Interactively prompt for common settings and write a fhirlint.yml
to the current directory.

Run with --force to overwrite an existing fhirlint.yml.`,
	RunE: runInit,
}

var flagInitForce bool

func init() {
	initCmd.Flags().BoolVar(&flagInitForce, "force", false, "Overwrite existing fhirlint.yml")
	rootCmd.AddCommand(initCmd)
}

func runInit(_ *cobra.Command, _ []string) error {
	const configFile = "fhirlint.yml"

	if _, err := os.Stat(configFile); err == nil && !flagInitForce {
		return fmt.Errorf("%s already exists — use --force to overwrite", configFile)
	}

	sc := bufio.NewScanner(os.Stdin)

	txServer := prompt(sc, "Terminology server", "https://tx.fhir.org")
	disableTx := promptBool(sc, "Disable terminology server", false)
	igRaw := prompt(sc, "IGs to load (comma-separated, e.g. kbv.basis#1.5.0)", "")
	failOn := promptChoice(sc, "Severity to fail on", "error", []string{"error", "warning", "information", "never"})

	var sb strings.Builder
	sb.WriteString("# fhirlint.yml — generated by fhirlint init\n")
	sb.WriteString("# See fhirlint.yml.example for all available options.\n\n")

	sb.WriteString(fmt.Sprintf("fail-on: %s\n\n", failOn))

	if disableTx {
		sb.WriteString("no-terminology-server: true\n\n")
	} else if txServer != "https://tx.fhir.org" {
		sb.WriteString(fmt.Sprintf("terminology-server: %s\n\n", txServer))
	}

	if igRaw != "" {
		sb.WriteString("ig:\n")
		for _, ig := range splitCSV(igRaw) {
			sb.WriteString(fmt.Sprintf("  - %s\n", ig))
		}
		sb.WriteString("\n")
	}

	if err := os.WriteFile(configFile, []byte(sb.String()), 0600); err != nil {
		return fmt.Errorf("writing %s: %w", configFile, err)
	}
	fmt.Fprintf(os.Stderr, "✓ Written %s\n", configFile)
	return nil
}

func prompt(sc *bufio.Scanner, question, defaultVal string) string {
	if defaultVal != "" {
		fmt.Fprintf(os.Stderr, "? %s [%s]: ", question, defaultVal)
	} else {
		fmt.Fprintf(os.Stderr, "? %s: ", question)
	}
	if sc.Scan() {
		if v := strings.TrimSpace(sc.Text()); v != "" {
			return v
		}
	}
	return defaultVal
}

func promptBool(sc *bufio.Scanner, question string, defaultVal bool) bool {
	def := "no"
	if defaultVal {
		def = "yes"
	}
	fmt.Fprintf(os.Stderr, "? %s [%s]: ", question, def)
	if sc.Scan() {
		switch strings.ToLower(strings.TrimSpace(sc.Text())) {
		case "y", "yes", "true", "1":
			return true
		case "n", "no", "false", "0":
			return false
		}
	}
	return defaultVal
}

func promptChoice(sc *bufio.Scanner, question, defaultVal string, choices []string) string {
	fmt.Fprintf(os.Stderr, "? %s [%s] (%s): ", question, defaultVal, strings.Join(choices, "/"))
	if sc.Scan() {
		v := strings.TrimSpace(sc.Text())
		for _, c := range choices {
			if strings.EqualFold(v, c) {
				return c
			}
		}
	}
	return defaultVal
}

func splitCSV(s string) []string {
	var out []string
	for _, part := range strings.Split(s, ",") {
		if v := strings.TrimSpace(part); v != "" {
			out = append(out, v)
		}
	}
	return out
}
